/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_MySQLConnection;

import java.awt.print.PrinterException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.MessageFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Mostafa Khaled
 */
public class Java_MySQLConnection extends javax.swing.JFrame {

    /**
     * Creates new form Java_MySQLConnection
     */
    
    private static final String username = "root";
    private static final String password = "";
    private static final String database = "jdbc:mysql://localhost/school_management_system";
    
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;
    
    int q, i, id, deleteItem;
    public Java_MySQLConnection() {
        initComponents();
        updateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void updateDB(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(database, username, password);
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM students");
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount(); // 7
            
            DefaultTableModel recordTable = (DefaultTableModel)jTable1.getModel();
            recordTable.setRowCount(0);
            while(rs.next()){
                Vector columnData = new Vector();
                columnData.add(rs.getShort("id"));
                columnData.add(rs.getString("student_id"));
                columnData.add(rs.getString("first_name"));
                columnData.add(rs.getString("last_name"));
                columnData.add(rs.getString("address"));
                columnData.add(rs.getString("post_code"));
                columnData.add(rs.getString("telephone"));

                recordTable.addRow(columnData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtStudentID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtLastname = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtPostCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtTelephone = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCHOOL MANAGEMENT SYSTEM");
        setMinimumSize(new java.awt.Dimension(1015, 840));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 210, 70));

        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 210, 70));

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, 70));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 210, 70));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, 70));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 210, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 280, 620));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jtxtStudentID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentIDActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 460, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Firstname");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstnameActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 460, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Lastname");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jtxtLastname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLastnameActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 460, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAddressActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 460, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Address");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Post Code");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPostCodeActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 460, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Telephone");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jtxtTelephone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelephoneActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 460, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 650, 350));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setText("SCHOOL MANAGEMENT SYSTEM");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 940, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Student ID", "Firstname", "Lastname", "Address", "Post Code", "Telephone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 650, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStudentIDActionPerformed

    private void jtxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstnameActionPerformed

    private void jtxtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLastnameActionPerformed

    private void jtxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAddressActionPerformed

    private void jtxtPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPostCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPostCodeActionPerformed

    private void jtxtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelephoneActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(database, username, password);
            st = conn.createStatement();
            String query = "INSERT INTO students (student_id, first_name, last_name, address, post_code, telephone) VALUES ("
                    + "'"+jtxtStudentID.getText()+"', "
                    + "'"+jtxtFirstname.getText()+"', "
                    + "'"+jtxtLastname.getText()+"', "
                    + "'"+jtxtAddress.getText()+"',"
                    + "'"+jtxtPostCode.getText()+"',"
                    + "'"+jtxtTelephone.getText()+"')"; 
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Record Added");
            updateDB();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Students Data");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException e) {
            System.err.format("No Printer Found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed
    
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Are you sure that you want to exit?", "Exit", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtStudentID.setText("");
        jtxtFirstname.setText("");
        jtxtLastname.setText("");
        jtxtAddress.setText("");
        jtxtPostCode.setText("");
        jtxtTelephone.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(database, username, password);
            st = conn.createStatement();
            String query = "UPDATE students SET student_id = "
                    + "'"+jtxtStudentID.getText()+"', "
                    + "first_name = '"+jtxtFirstname.getText()+"', "
                    + "last_name = '"+jtxtLastname.getText()+"', "
                    + "address = '"+jtxtAddress.getText()+"',"
                    + "post_code = '"+jtxtPostCode.getText()+"',"
                    + "telephone = '"+jtxtTelephone.getText()+"' WHERE student_id = " + jtxtStudentID.getText(); 
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Record Updated");
            updateDB();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel recordTable = (DefaultTableModel)jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        jtxtStudentID.setText(recordTable.getValueAt(selectedRow, 1).toString());
        jtxtFirstname.setText(recordTable.getValueAt(selectedRow, 2).toString());
        jtxtLastname.setText(recordTable.getValueAt(selectedRow, 3).toString());
        jtxtAddress.setText(recordTable.getValueAt(selectedRow, 4).toString());
        jtxtPostCode.setText(recordTable.getValueAt(selectedRow, 5).toString());
        jtxtTelephone.setText(recordTable.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel recordTable = (DefaultTableModel)jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        try{
            id =  Integer.parseInt(recordTable.getValueAt(selectedRow, 0).toString());
            deleteItem = JOptionPane.showConfirmDialog(null, "Are you sure that you want to delete this record?", "Warning", JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection(database, username, password);
                st = conn.createStatement();
                String query = "DELETE FROM students WHERE student_id = " + id; 
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Record Deleted");
                updateDB();
                jtxtStudentID.setText("");
                jtxtFirstname.setText("");
                jtxtLastname.setText("");
                jtxtAddress.setText("");
                jtxtPostCode.setText("");
                jtxtTelephone.setText("");
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_MySQLConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_MySQLConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_MySQLConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_MySQLConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java_MySQLConnection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtLastname;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtTelephone;
    // End of variables declaration//GEN-END:variables
}
